### ISSUE TITLE
Internal service demand

### ISSUE THREAD

**Issue by robs74** [robs74/offices-generate-money#3]
People demand some services and you have to supply them, otherwise, your workers become unhappy or less loyal. You can only export excess services.

**Comment by marcelinorc** [comment]
Hey Rob... I don't think this makes sense. If a worker works in the office, this means he/she is not needed elsewhere (a factory, hospital, school, etc.). On the contrary, if due to having too many workers in the office the schools, hospitals, and stores are lacking manpower, the game mechanics will already punish you. What do you think?

**Comment by robs74** [comment]
This is supposed to make the system symmetric, you don't only export services, but also need some internally, so services become a kind of invisible good. I'm already working on implementing this, you'll see. Obviously, it makes the game harder. In any case, the feature is supposed to be modular so if someone doesn't like it they can disable it in a settings file.
